'use client';
import type { SoftSkillsReport } from '@/lib/soft-skills-engine';

function Bar({ value, color }: { value: number; color: string }) {
  return (
    <div className="w-full h-2.5 bg-white/5 rounded-full overflow-hidden mt-1">
      <div className="h-full rounded-full transition-all duration-700" style={{ width: `${value}%`, background: color }} />
    </div>
  );
}

export default function SoftSkillsReportView({ report, studentName }: { report: SoftSkillsReport; studentName: string }) {
  const downloadPDF = () => {
    const pw = window.open('', '_blank');
    if (!pw) { alert('Please allow popups to download PDF.'); return; }
    const sc = report.overallScore >= 70 ? '#22c55e' : report.overallScore >= 50 ? '#f59e0b' : '#ef4444';
    const gc = report.grade === 'Excellent' ? '#22c55e' : report.grade === 'Good' ? '#3b82f6' : report.grade === 'Average' ? '#f59e0b' : '#ef4444';
    const html = `<!DOCTYPE html><html><head><title>Soft Skills Report - ${studentName}</title><style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Segoe UI',sans-serif;background:#fff;color:#111;padding:40px}
.header{background:linear-gradient(135deg,#0f0f1a,#1a1a2e);color:white;padding:30px;border-radius:12px;margin-bottom:24px}
.logo{font-size:24px;font-weight:900;color:#06b6d4}.sub{color:#94a3b8;font-size:13px;margin-top:4px}
.sname{font-size:20px;font-weight:700;color:white;margin-top:12px}.sdate{color:#94a3b8;font-size:12px;margin-top:4px}
.score-big{font-size:72px;font-weight:900;text-align:center;margin:16px 0;color:${sc}}
.grade{display:inline-block;padding:4px 16px;border-radius:20px;font-weight:700;font-size:14px;background:${gc};color:white}
.center{text-align:center;margin-bottom:24px}.mrow{display:flex;gap:16px;margin-bottom:16px}
.mcard{flex:1;border:1px solid #e5e7eb;border-radius:8px;padding:16px;text-align:center}
.mval{font-size:32px;font-weight:900;color:#06b6d4}.mlbl{font-size:12px;color:#6b7280;margin-top:4px}
.section{border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:16px}
.stitle{font-size:14px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:1px;margin-bottom:12px}
.ci{display:flex;align-items:flex-start;gap:10px;padding:10px 0;border-bottom:1px solid #f3f4f6}
.ci:last-child{border-bottom:none}.cicon{font-size:18px}.ct{font-weight:600;font-size:14px}.ctip{font-size:12px;color:#6b7280;margin-top:2px}
.footer{text-align:center;margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:12px}
@media print{body{padding:20px}}</style></head><body>
<div class="header"><div class="logo">SmartPRS</div><div class="sub">Soft Skills Analysis Report</div>
<div class="sname">${studentName}</div><div class="sdate">${new Date().toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</div></div>
<div class="center"><div class="score-big">${report.overallScore}</div><div style="color:#6b7280;font-size:14px">out of 100</div><div class="grade">${report.grade}</div></div>
<div class="mrow"><div class="mcard"><div class="mval">${report.avgConfidence}</div><div class="mlbl">Confidence</div></div>
<div class="mcard"><div class="mval">${report.avgClarity}</div><div class="mlbl">Clarity</div></div>
<div class="mcard"><div class="mval">${report.avgWords}</div><div class="mlbl">Words Spoken</div></div></div>
<div class="section"><div class="stitle">Answer Structure</div>
<div class="ci"><span class="cicon">${report.hasIntro?'✅':'❌'}</span><div><div class="ct">Introduction ${report.hasIntro?'Detected':'Missing'}</div><div class="ctip">${report.hasIntro?'Good opening detected':'Start with "I am..." or "Let me..."'}</div></div></div>
<div class="ci"><span class="cicon">${report.hasBody?'✅':'❌'}</span><div><div class="ct">Body/Examples ${report.hasBody?'Present':'Missing'}</div><div class="ctip">${report.hasBody?'Supporting examples found':'Add "For example..." or real stories'}</div></div></div>
<div class="ci"><span class="cicon">${report.hasConclusion?'✅':'❌'}</span><div><div class="ct">Conclusion ${report.hasConclusion?'Present':'Missing'}</div><div class="ctip">${report.hasConclusion?'Good wrap-up detected':'End with "So that is why..." or a summary'}</div></div></div></div>
<div class="section"><div class="stitle">Filler Words</div><div style="font-size:15px;font-weight:600;color:${report.totalFillers===0?'#22c55e':'#f59e0b'}">${report.totalFillers===0?'✅ None detected — excellent control!':'⚠️ '+report.totalFillers+' filler words: '+report.allFillers.join(', ')}</div></div>
<div class="section"><div class="stitle">Top Recommendation</div><div style="font-size:14px;line-height:1.6">${report.topTip}</div></div>
<div class="footer">Generated by SmartPRS · Vidyavardhaka College of Engineering, Mysuru · SYMBIOT Hackathon 2026</div>
</body></html>`;
    pw.document.write(html); pw.document.close();
    pw.onload = () => { pw.print(); };
  };

  const gcl = report.grade === 'Excellent' ? 'text-emerald-400 bg-emerald-500/20' :
    report.grade === 'Good' ? 'text-cyan-400 bg-cyan-500/20' :
    report.grade === 'Average' ? 'text-yellow-400 bg-yellow-500/20' : 'text-red-400 bg-red-500/20';

  const wl = report.avgWords >= 80 ? 'Excellent' : report.avgWords >= 40 ? 'Good' : report.avgWords >= 15 ? 'Short' : 'Too short';
  const wc = report.avgWords >= 40 ? 'text-emerald-400' : report.avgWords >= 15 ? 'text-yellow-400' : 'text-red-400';

  return (
    <div className="space-y-5 animate-fade-in">
      {/* 1. Score */}
      <div className="text-center pb-5 border-b border-white/10">
        <div className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-brand-cyan to-brand-purple my-2">{report.overallScore}</div>
        <span className={`text-xs font-bold uppercase px-3 py-1 rounded-full ${gcl}`}>{report.grade}</span>
        <div className="mt-3">
          <button onClick={downloadPDF} className="text-xs font-semibold px-4 py-2 rounded-lg bg-brand-cyan/20 text-brand-cyan hover:bg-brand-cyan/30 transition">⬇ Download as PDF</button>
        </div>
      </div>

      {/* 2. Metrics */}
      <div className="grid grid-cols-3 gap-3">
        <div className="p-3 rounded-xl bg-white/3 border border-white/5 text-center">
          <p className="text-[10px] text-gray-500 uppercase mb-1">🎯 Confidence</p>
          <p className="text-xl font-bold text-cyan-400">{report.avgConfidence}</p>
          <Bar value={report.avgConfidence} color="#06B6D4" />
        </div>
        <div className="p-3 rounded-xl bg-white/3 border border-white/5 text-center">
          <p className="text-[10px] text-gray-500 uppercase mb-1">💬 Clarity</p>
          <p className="text-xl font-bold text-purple-400">{report.avgClarity}</p>
          <Bar value={report.avgClarity} color="#8B5CF6" />
        </div>
        <div className="p-3 rounded-xl bg-white/3 border border-white/5 text-center">
          <p className="text-[10px] text-gray-500 uppercase mb-1">📝 Words</p>
          <p className="text-xl font-bold text-gray-200">{report.avgWords}</p>
          <p className={`text-[10px] mt-1 ${wc}`}>{wl}</p>
        </div>
      </div>

      {/* 3. What Worked */}
      {report.whatWorked.length > 0 && (
        <div className="p-4 rounded-xl bg-emerald-500/5 border border-emerald-500/20">
          <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider mb-2">✅ What Worked</h4>
          {report.whatWorked.map((w, i) => <p key={i} className="text-sm text-emerald-300/80 py-1">✅ {w}</p>)}
        </div>
      )}

      {/* 4. What to Improve */}
      {report.whatToImprove.length > 0 && (
        <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/20">
          <h4 className="text-xs font-bold text-red-400 uppercase tracking-wider mb-2">❌ What to Improve</h4>
          {report.whatToImprove.map((w, i) => (
            <div key={i} className="py-1.5">
              <p className="text-sm text-red-300/80">❌ {w.issue}</p>
              <p className="text-xs text-gray-500 ml-5 mt-0.5">→ {w.tip}</p>
            </div>
          ))}
        </div>
      )}

      {/* 5. Fillers + Top Tip */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <div className="p-4 rounded-xl bg-white/3 border border-white/5">
          <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-2">🗣️ Filler Words</h4>
          {report.totalFillers === 0 ? (
            <p className="text-sm text-emerald-400">✅ None detected — excellent!</p>
          ) : (
            <div>
              <p className="text-sm text-yellow-400 mb-2">{report.totalFillers} filler{report.totalFillers > 1 ? 's' : ''} found</p>
              <div className="flex flex-wrap gap-1.5">{report.allFillers.map(f => <span key={f} className="px-2 py-0.5 text-[10px] font-bold bg-yellow-500/20 text-yellow-400 rounded-full">{f}</span>)}</div>
            </div>
          )}
        </div>
        <div className="p-4 rounded-xl bg-brand-cyan/5 border border-brand-cyan/20">
          <h4 className="text-xs font-bold text-brand-cyan uppercase tracking-wider mb-2">💡 Top Recommendation</h4>
          <p className="text-sm text-gray-300 leading-relaxed">{report.topTip}</p>
        </div>
      </div>
    </div>
  );
}
