'use client';
import type { SoftSkillsReport } from '@/lib/soft-skills-engine';

function Bar({ value, color }: { value: number; color: string }) {
  return (
    <div className="w-full h-3 bg-[#F8F7FF] border-2 border-[#1A1035] rounded-full overflow-hidden mt-1 shadow-[inset_0px_2px_4px_rgba(0,0,0,0.05)]">
      <div className="h-full border-r-2 border-[#1A1035] transition-all duration-700" style={{ width: `${value}%`, background: color }} />
    </div>
  );
}

export default function SoftSkillsReportView({ report, studentName }: { report: SoftSkillsReport; studentName: string }) {
  const downloadPDF = () => {
    const pw = window.open('', '_blank');
    if (!pw) { alert('Please allow popups to download PDF.'); return; }
    const sc = report.overallScore >= 70 ? '#22c55e' : report.overallScore >= 50 ? '#f59e0b' : '#ef4444';
    const gc = report.grade === 'Excellent' ? '#22c55e' : report.grade === 'Good' ? '#3b82f6' : report.grade === 'Average' ? '#f59e0b' : '#ef4444';
    const html = `<!DOCTYPE html><html><head><title>Soft Skills Report - ${studentName}</title><style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Segoe UI',sans-serif;background:#fff;color:#111;padding:40px}
.header{background:linear-gradient(135deg,#0f0f1a,#1a1a2e);color:white;padding:30px;border-radius:12px;margin-bottom:24px}
.logo{font-size:24px;font-weight:900;color:#06b6d4}.sub{color:#94a3b8;font-size:13px;margin-top:4px}
.sname{font-size:20px;font-weight:700;color:white;margin-top:12px}.sdate{color:#94a3b8;font-size:12px;margin-top:4px}
.score-big{font-size:72px;font-weight:900;text-align:center;margin:16px 0;color:${sc}}
.grade{display:inline-block;padding:4px 16px;border-radius:20px;font-weight:700;font-size:14px;background:${gc};color:white}
.center{text-align:center;margin-bottom:24px}.mrow{display:flex;gap:16px;margin-bottom:16px}
.mcard{flex:1;border:1px solid #e5e7eb;border-radius:8px;padding:16px;text-align:center}
.mval{font-size:32px;font-weight:900;color:#06b6d4}.mlbl{font-size:12px;color:#6b7280;margin-top:4px}
.section{border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:16px}
.stitle{font-size:14px;font-weight:700;color:#6b7280;text-transform:uppercase;letter-spacing:1px;margin-bottom:12px}
.ci{display:flex;align-items:flex-start;gap:10px;padding:10px 0;border-bottom:1px solid #f3f4f6}
.ci:last-child{border-bottom:none}.cicon{font-size:18px}.ct{font-weight:600;font-size:14px}.ctip{font-size:12px;color:#6b7280;margin-top:2px}
.footer{text-align:center;margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:12px}
@media print{body{padding:20px}}</style></head><body>
<div class="header"><div class="logo">SmartPRS</div><div class="sub">Soft Skills Analysis Report</div>
<div class="sname">${studentName}</div><div class="sdate">${new Date().toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</div></div>
<div class="center"><div class="score-big">${report.overallScore}</div><div style="color:#6b7280;font-size:14px">out of 100</div><div class="grade">${report.grade}</div></div>
<div class="mrow"><div class="mcard"><div class="mval">${report.avgConfidence}</div><div class="mlbl">Confidence</div></div>
<div class="mcard"><div class="mval">${report.avgClarity}</div><div class="mlbl">Clarity</div></div>
<div class="mcard"><div class="mval">${report.avgWords}</div><div class="mlbl">Words Spoken</div></div></div>
<div class="section"><div class="stitle">Answer Structure</div>
<div class="ci"><span class="cicon">${report.hasIntro?'✅':'❌'}</span><div><div class="ct">Introduction ${report.hasIntro?'Detected':'Missing'}</div><div class="ctip">${report.hasIntro?'Good opening detected':'Start with "I am..." or "Let me..."'}</div></div></div>
<div class="ci"><span class="cicon">${report.hasBody?'✅':'❌'}</span><div><div class="ct">Body/Examples ${report.hasBody?'Present':'Missing'}</div><div class="ctip">${report.hasBody?'Supporting examples found':'Add "For example..." or real stories'}</div></div></div>
<div class="ci"><span class="cicon">${report.hasConclusion?'✅':'❌'}</span><div><div class="ct">Conclusion ${report.hasConclusion?'Present':'Missing'}</div><div class="ctip">${report.hasConclusion?'Good wrap-up detected':'End with "So that is why..." or a summary'}</div></div></div></div>
<div class="section"><div class="stitle">Filler Words</div><div style="font-size:15px;font-weight:600;color:${report.totalFillers===0?'#22c55e':'#f59e0b'}">${report.totalFillers===0?'✅ None detected — excellent control!':'⚠️ '+report.totalFillers+' filler words: '+report.allFillers.join(', ')}</div></div>
<div class="section"><div class="stitle">Top Recommendation</div><div style="font-size:14px;line-height:1.6">${report.topTip}</div></div>
<div class="footer">Generated by SmartPRS · Vidyavardhaka College of Engineering, Mysuru · SYMBIOT Hackathon 2026</div>
</body></html>`;
    pw.document.write(html); pw.document.close();
    pw.onload = () => { pw.print(); };
  };

  const wl = report.avgWords >= 80 ? 'Excellent' : report.avgWords >= 40 ? 'Good' : report.avgWords >= 15 ? 'Short' : 'Too short';

  return (
    <div className="space-y-5 animate-fade-in">
      {/* 1. Score */}
      <div className="text-center pb-6 border-b-4 border-[#1A1035]/10">
        <div className="text-6xl font-black text-[#1A1035] my-2 drop-shadow-[4px_4px_0px_rgba(26,16,53,0.2)]">{report.overallScore}</div>
        <span className={`text-[10px] font-black uppercase tracking-widest px-3 py-1 rounded border-2 border-[#1A1035] shadow-[2px_2px_0px_#1A1035] ${
          report.grade === 'Excellent' ? 'bg-[#00C9A7] text-[#1A1035]' : 
          report.grade === 'Good' ? 'bg-[#6C47FF] text-white' : 
          report.grade === 'Average' ? 'bg-[#FFB347] text-[#1A1035]' : 'bg-[#FF4D6D] text-white'
        }`}>{report.grade}</span>
        <div className="mt-4">
          <button onClick={downloadPDF} className="text-[10px] font-black uppercase tracking-widest px-4 py-2 rounded-xl bg-white border-2 border-[#1A1035] text-[#1A1035] shadow-[2px_2px_0px_#1A1035] hover:shadow-[4px_4px_0px_#1A1035] hover:-translate-y-0.5 transition-all">⬇ Download as PDF</button>
        </div>
      </div>

      {/* 2. Metrics */}
      <div className="grid grid-cols-3 gap-4">
        <div className="p-4 rounded-xl bg-[#F8F7FF] border-2 border-[#1A1035] text-center shadow-[4px_4px_0px_#1A1035]">
          <p className="text-[10px] text-[#1A1035]/60 font-black uppercase tracking-widest mb-1">🎯 Confidence</p>
          <p className="text-2xl font-black text-[#1A1035] mb-1">{report.avgConfidence}</p>
          <Bar value={report.avgConfidence} color="#00C9A7" />
        </div>
        <div className="p-4 rounded-xl bg-[#F8F7FF] border-2 border-[#1A1035] text-center shadow-[4px_4px_0px_#1A1035]">
          <p className="text-[10px] text-[#1A1035]/60 font-black uppercase tracking-widest mb-1">💬 Clarity</p>
          <p className="text-2xl font-black text-[#1A1035] mb-1">{report.avgClarity}</p>
          <Bar value={report.avgClarity} color="#6C47FF" />
        </div>
        <div className="p-4 rounded-xl bg-[#F8F7FF] border-2 border-[#1A1035] text-center shadow-[4px_4px_0px_#1A1035]">
          <p className="text-[10px] text-[#1A1035]/60 font-black uppercase tracking-widest mb-1">📝 Words</p>
          <p className="text-2xl font-black text-[#1A1035]">{report.avgWords}</p>
          <p className={`text-[10px] font-black uppercase tracking-widest mt-1 ${
            report.avgWords >= 40 ? 'text-[#00C9A7]' : report.avgWords >= 15 ? 'text-[#FFB347]' : 'text-[#FF4D6D]'
          }`}>{wl}</p>
        </div>
      </div>

      {/* 3. What Worked */}
      {report.whatWorked.length > 0 && (
        <div className="p-5 rounded-xl bg-[#00C9A7]/10 border-2 border-[#1A1035] shadow-[4px_4px_0px_#1A1035]">
          <h4 className="text-[10px] font-black text-[#00C9A7] uppercase tracking-widest mb-3 bg-[#1A1035] inline-block px-2 py-1 rounded">✅ What Worked</h4>
          {report.whatWorked.map((w, i) => <p key={i} className="text-sm font-bold text-[#1A1035] py-1 flex items-start gap-2"><span className="shrink-0 mt-0.5">✅</span> <span>{w}</span></p>)}
        </div>
      )}

      {/* 4. What to Improve */}
      {report.whatToImprove.length > 0 && (
        <div className="p-5 rounded-xl bg-[#FF4D6D]/10 border-2 border-[#1A1035] shadow-[4px_4px_0px_#1A1035]">
          <h4 className="text-[10px] font-black text-[#FF4D6D] uppercase tracking-widest mb-3 bg-[#1A1035] inline-block px-2 py-1 rounded">❌ What to Improve</h4>
          {report.whatToImprove.map((w, i) => (
            <div key={i} className="py-2">
              <p className="text-sm font-bold text-[#1A1035] flex items-start gap-2"><span className="shrink-0 mt-0.5">❌</span> <span>{w.issue}</span></p>
              <p className="text-xs font-bold text-[#1A1035]/60 ml-7 mt-1 flex items-start gap-1"><span className="shrink-0">→</span> <span>{w.tip}</span></p>
            </div>
          ))}
        </div>
      )}

      {/* 5. Fillers + Top Tip */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="p-5 rounded-xl bg-white border-2 border-[#1A1035] shadow-[4px_4px_0px_#1A1035]">
          <h4 className="text-[10px] font-black text-[#1A1035] uppercase tracking-widest mb-3 border-b-2 border-[#1A1035]/10 pb-2">🗣️ Filler Words</h4>
          {report.totalFillers > 0 ? (
            <div>
              <p style={{color: '#f59e0b'}}>
                ⚠️ {report.totalFillers} filler word types detected:
              </p>
              <div style={{
                display: 'flex', 
                flexWrap: 'wrap', 
                gap: '8px',
                marginTop: '8px'
              }}>
                {report.allFillers.map((f, i) => (
                  <span key={i} style={{
                    background: 'rgba(245,158,11,0.15)',
                    border: '1px solid rgba(245,158,11,0.4)',
                    color: '#f59e0b',
                    padding: '4px 12px',
                    borderRadius: '20px',
                    fontSize: '13px',
                    fontWeight: 600
                  }}>
                    {f}
                  </span>
                ))}
              </div>
              <p style={{
                color: '#94a3b8', 
                fontSize: '12px',
                marginTop: '8px'
              }}>
                Tip: Replace fillers with a brief pause instead.
              </p>
            </div>
          ) : (
            <div style={{
              color: '#22c55e',
              fontWeight: 600
            }}>
              ✅ No filler words detected — excellent speech control!
            </div>
          )}
        </div>
        <div className="p-5 rounded-xl bg-[#6C47FF]/10 border-2 border-[#1A1035] shadow-[4px_4px_0px_#1A1035]">
          <h4 className="text-[10px] font-black text-[#6C47FF] uppercase tracking-widest mb-3 border-b-2 border-[#1A1035]/10 pb-2">💡 Top Recommendation</h4>
          <p className="text-sm font-bold text-[#1A1035] leading-relaxed">{report.topTip}</p>
        </div>
      </div>
    </div>
  );
}
