export const QUESTION_BANK = {
  aptitude: [
    { id: 'apt_001', question: 'A train travels 360 km in 4 hours. What is its speed in m/s?', options: ['20 m/s', '25 m/s', '30 m/s', '15 m/s'], correct: 1, explanation: '360 km/4 hrs = 90 km/hr = 90 × (1000/3600) = 25 m/s' },
    { id: 'apt_002', question: 'If 12 workers finish a job in 8 days, how many days will 16 workers take?', options: ['4 days', '5 days', '6 days', '7 days'], correct: 2, explanation: '12×8 = 16×d → d = 6 days' },
    { id: 'apt_003', question: 'Find the odd one: 2, 5, 10, 17, 26, 37, 50, 64', options: ['37', '50', '64', '26'], correct: 2, explanation: 'Pattern: n²+1. Should be 65 not 64.' },
    { id: 'apt_004', question: 'A can do a work in 15 days and B in 20 days. In how many days together?', options: ['8.5 days', '8.57 days', '9 days', '10 days'], correct: 1, explanation: '1/15 + 1/20 = 7/60, so 60/7 ≈ 8.57 days' },
    { id: 'apt_005', question: 'The ratio of ages of A and B is 3:5. After 10 years, ratio is 5:7. Age of B?', options: ['20', '25', '30', '35'], correct: 1, explanation: '3x+10/5x+10 = 5/7 → x=5, B = 5×5 = 25' },
    { id: 'apt_006', question: 'Simple interest on ₹5000 at 8% per year for 3 years?', options: ['₹1000', '₹1200', '₹1500', '₹1800'], correct: 1, explanation: 'SI = 5000×8×3/100 = ₹1200' },
    { id: 'apt_007', question: 'If ROAD is coded as 2415, how is LOAD coded?', options: ['1215', '1512', '1213', '1415'], correct: 0, explanation: 'L=1, O=2, A=1, D=5 → 1215' },
    { id: 'apt_008', question: 'A shopkeeper sells at 20% profit. Cost price is ₹500. Selling price?', options: ['₹550', '₹580', '₹600', '₹620'], correct: 2, explanation: 'SP = 500 + 20% of 500 = ₹600' },
    { id: 'apt_009', question: 'Find next: 1, 1, 2, 3, 5, 8, 13, ?', options: ['18', '21', '20', '19'], correct: 1, explanation: 'Fibonacci: 8+13 = 21' },
    { id: 'apt_010', question: 'Pipes A and B fill a tank in 20 and 30 mins. Pipe C empties in 15 mins. All open — time to fill?', options: ['60 min', '120 min', 'Never fills', '90 min'], correct: 2, explanation: 'Net = 1/20+1/30-1/15 = -1/60 (negative — never fills)' },
    { id: 'apt_011', question: 'Average of 5 numbers is 27. If one number is excluded, average is 25. Excluded number?', options: ['30', '35', '27', '32'], correct: 1, explanation: '5×27 - 4×25 = 135 - 100 = 35' },
    { id: 'apt_012', question: 'LCM of 12, 15, 20, 27?', options: ['540', '1080', '270', '360'], correct: 0, explanation: 'LCM(12,15,20,27) = 540' },
    { id: 'apt_013', question: 'A is 40% more efficient than B. B can complete in 21 days. A+B together?', options: ['10 days', '9 days', '12 days', '11 days'], correct: 1, explanation: 'A = 1.4/21, B = 1/21, together = 2.4/21 = 21/2.4 ≈ 8.75 ≈ 9 days' },
    { id: 'apt_014', question: 'Compound interest on ₹10000 at 10% for 2 years (annually)?', options: ['₹2000', '₹2100', '₹1000', '₹2500'], correct: 1, explanation: '10000×(1.1)² - 10000 = 12100 - 10000 = ₹2100' },
    { id: 'apt_015', question: 'A can complete a task in 12 days, B in 18 days. They work together for 4 days. Remaining work done by A alone in?', options: ['4 days', '5 days', '6 days', '7 days'], correct: 1, explanation: 'In 4 days together: 4(1/12+1/18)=4×5/36=20/36=5/9. Remaining=4/9. A does 4/9÷1/12=5.33≈5 days' },
  ],
  coding: [
    { id: 'code_001', question: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], correct: 1, explanation: 'Binary search halves the search space each time → O(log n)' },
    { id: 'code_002', question: 'Which data structure uses LIFO (Last In First Out)?', options: ['Queue', 'Stack', 'LinkedList', 'Tree'], correct: 1, explanation: 'Stack follows LIFO — last element pushed is first popped' },
    { id: 'code_003', question: 'What does SQL SELECT DISTINCT do?', options: ['Sorts results', 'Returns unique rows', 'Counts rows', 'Filters nulls'], correct: 1, explanation: 'DISTINCT eliminates duplicate rows from result set' },
    { id: 'code_004', question: "Output of: print(type([])) in Python?", options: ["<class 'list'>", "<class 'array'>", "<class 'tuple'>", 'Error'], correct: 0, explanation: '[] creates a list object in Python' },
    { id: 'code_005', question: 'Which sorting algorithm has worst case O(n log n)?', options: ['Bubble Sort', 'Quick Sort', 'Merge Sort', 'Insertion Sort'], correct: 2, explanation: 'Merge Sort is always O(n log n) in all cases' },
    { id: 'code_006', question: 'In a BST, inorder traversal gives elements in:', options: ['Random order', 'Reverse sorted', 'Sorted ascending', 'Level order'], correct: 2, explanation: 'Inorder (Left-Root-Right) on BST always gives sorted ascending order' },
    { id: 'code_007', question: 'What is a deadlock in OS?', options: ['Memory overflow', 'Processes waiting for each other forever', 'CPU overheating', 'Disk failure'], correct: 1, explanation: 'Deadlock: circular wait where processes hold resources and wait for others' },
    { id: 'code_008', question: 'Which HTTP method is idempotent AND safe?', options: ['POST', 'PUT', 'GET', 'DELETE'], correct: 2, explanation: 'GET is both safe (no side effects) and idempotent (same result repeated)' },
    { id: 'code_009', question: 'What is the output?\nfor i in range(3):\n    print(i, end=" ")', options: ['1 2 3', '0 1 2', '0 1 2 3', '1 2'], correct: 1, explanation: 'range(3) generates 0, 1, 2' },
    { id: 'code_010', question: 'A graph with V vertices and E edges — DFS time complexity?', options: ['O(V)', 'O(E)', 'O(V+E)', 'O(V×E)'], correct: 2, explanation: 'DFS visits every vertex and edge once → O(V+E)' },
    { id: 'code_011', question: 'Which JOIN returns all rows from both tables, matched where possible?', options: ['INNER JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 'CROSS JOIN'], correct: 2, explanation: 'FULL OUTER JOIN returns all rows from both tables' },
    { id: 'code_012', question: 'What does "git rebase" do?', options: ['Deletes a branch', 'Moves commits to a new base', 'Creates a tag', 'Merges with conflict'], correct: 1, explanation: 'Rebase moves/reapplies commits on top of another branch' },
    { id: 'code_013', question: 'Fibonacci using dynamic programming reduces complexity from O(2^n) to:', options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(log n)'], correct: 2, explanation: 'Memoization stores subproblem results → linear time O(n)' },
    { id: 'code_014', question: 'In React, what hook manages side effects?', options: ['useState', 'useEffect', 'useContext', 'useRef'], correct: 1, explanation: 'useEffect runs side effects after render (API calls, subscriptions)' },
    { id: 'code_015', question: 'What is normalization in databases?', options: ['Encrypting data', 'Reducing data redundancy and improving integrity', 'Speeding up queries', 'Backing up data'], correct: 1, explanation: 'Normalization organizes DB to reduce redundancy (1NF, 2NF, 3NF, BCNF)' },
  ],
  core_subjects: [
    { id: 'core_001', question: 'In OSI model, which layer handles routing?', options: ['Data Link', 'Transport', 'Network', 'Session'], correct: 2, explanation: 'Network layer (Layer 3) handles logical addressing and routing' },
    { id: 'core_002', question: 'What is a semaphore used for in OS?', options: ['Memory allocation', 'Process synchronization', 'CPU scheduling', 'Disk management'], correct: 1, explanation: 'Semaphores control access to shared resources — prevent race conditions' },
    { id: 'core_003', question: 'ACID properties in DBMS — what does "I" stand for?', options: ['Integration', 'Isolation', 'Indexing', 'Integrity'], correct: 1, explanation: 'Isolation ensures concurrent transactions do not interfere' },
    { id: 'core_004', question: 'Which is NOT a valid IPv4 address?', options: ['192.168.1.1', '256.0.0.1', '10.0.0.255', '172.16.0.1'], correct: 1, explanation: '256 is out of range — valid octets are 0–255' },
    { id: 'core_005', question: 'What is thrashing in OS?', options: ['Excessive CPU usage', 'Excessive paging causing low CPU utilization', 'Memory leak', 'Deadlock condition'], correct: 1, explanation: 'Thrashing: process spends more time swapping pages than executing' },
    { id: 'core_006', question: 'In TCP/IP, which protocol assigns IP addresses dynamically?', options: ['DNS', 'FTP', 'DHCP', 'ARP'], correct: 2, explanation: 'DHCP automatically assigns IP addresses to devices on a network' },
    { id: 'core_007', question: 'What does a compiler do?', options: ['Executes code line by line', 'Translates entire source code to machine code at once', 'Manages memory', 'Handles I/O operations'], correct: 1, explanation: 'Compiler translates entire high-level program to machine code before execution' },
    { id: 'core_008', question: 'Which page replacement algorithm has the least page faults theoretically?', options: ['FIFO', 'LRU', 'Optimal', 'Random'], correct: 2, explanation: 'Optimal algorithm replaces the page that will not be used longest — theoretical best' },
    { id: 'core_009', question: 'Third Normal Form (3NF) requires:', options: ['No partial dependencies', 'No transitive dependencies', 'No multi-valued dependencies', 'Atomic values only'], correct: 1, explanation: '3NF: no transitive dependency of non-key on primary key' },
    { id: 'core_010', question: 'What is the purpose of a Primary Key in a database?', options: ['Speed up joins', 'Uniquely identify each row', 'Encrypt data', 'Store foreign references'], correct: 1, explanation: 'Primary key uniquely identifies each record and cannot be NULL' },
    { id: 'core_011', question: 'Which scheduling algorithm can cause starvation?', options: ['Round Robin', 'FCFS', 'Priority Scheduling', 'SRTF'], correct: 2, explanation: 'Priority scheduling can starve low-priority processes indefinitely' },
    { id: 'core_012', question: 'In computer networks, what is a subnet mask used for?', options: ['Encrypt network traffic', 'Identify network and host portions of IP', 'Route between routers', 'Assign MAC addresses'], correct: 1, explanation: 'Subnet mask divides IP into network ID and host ID portions' },
    { id: 'core_013', question: 'Which is true about UDP vs TCP?', options: ['UDP is reliable, TCP is not', 'UDP is faster but no delivery guarantee', 'TCP does not need handshake', 'UDP is connection-oriented'], correct: 1, explanation: 'UDP: fast, no guarantee. TCP: reliable, ordered, connection-oriented' },
    { id: 'core_014', question: 'What is virtual memory?', options: ['RAM on the GPU', 'Using disk space as extension of RAM', 'Cache memory', 'ROM storage'], correct: 1, explanation: 'Virtual memory uses HDD/SSD to extend available RAM for processes' },
    { id: 'core_015', question: 'SQL GROUP BY is used with:', options: ['WHERE clause', 'Aggregate functions', 'Primary keys', 'Subqueries only'], correct: 1, explanation: 'GROUP BY works with COUNT, SUM, AVG, MAX, MIN to group result sets' },
  ],
  soft_skills: [
    { id: 'soft_001', question: 'In a group discussion, the best approach when someone disagrees with you is:', options: ['Stay silent to avoid conflict', 'Interrupt and repeat your point louder', 'Acknowledge their view and present your reasoning calmly', 'Change your opinion immediately'], correct: 2, explanation: 'Active listening + calm reasoning shows maturity and communication skill' },
    { id: 'soft_002', question: 'Your manager gives you a task with an impossible deadline. You should:', options: ['Accept silently and overwork', 'Refuse the task', 'Communicate constraints early and propose a realistic timeline', 'Do half the work and submit'], correct: 2, explanation: 'Proactive communication is key — good managers appreciate early flag' },
    { id: 'soft_003', question: 'Which is the most effective way to start a formal email?', options: ['Hey, quick question...', 'Dear [Name], I hope this message finds you well.', 'To whom it may concern, urgently...', 'Hi!! I am writing to ask...'], correct: 1, explanation: 'Professional greeting sets the right tone for formal communication' },
    { id: 'soft_004', question: 'During a presentation, you forget a key point. You should:', options: ['Panic and apologize repeatedly', 'Pause, take a breath, refer to notes naturally', 'Skip that section entirely', 'Ask the audience what comes next'], correct: 1, explanation: 'Composed recovery shows confidence — audience rarely notices brief pauses' },
    { id: 'soft_005', question: 'Active listening means:', options: ['Waiting for your turn to speak', 'Nodding constantly', 'Fully focusing, understanding, and responding thoughtfully', 'Taking notes only'], correct: 2, explanation: 'Active listening: focus + understand + remember + respond appropriately' },
    { id: 'soft_006', question: 'In a job interview, "Tell me about yourself" should focus on:', options: ['Your childhood and hobbies', 'Professional journey, skills, and why you are a fit', 'Family background', 'Complaints about previous college'], correct: 1, explanation: 'Keep it professional: education → skills → why this role. 90 seconds max.' },
    { id: 'soft_007', question: 'Which is NOT part of non-verbal communication?', options: ['Eye contact', 'Posture', 'Tone of voice', 'Word choice'], correct: 3, explanation: 'Word choice is verbal. Non-verbal: gestures, posture, eye contact, facial expressions' },
    { id: 'soft_008', question: 'A teammate is consistently missing deadlines. Best approach?', options: ['Report immediately to manager', 'Do their work yourself silently', 'Have a private, empathetic conversation first', 'Ignore it'], correct: 2, explanation: 'Direct but empathetic conversation often resolves issues before escalation' },
    { id: 'soft_009', question: 'STAR method in interviews stands for:', options: ['Skills, Tasks, Actions, Results', 'Situation, Task, Action, Result', 'Strategy, Target, Approach, Review', 'Strength, Thinking, Attitude, Resilience'], correct: 1, explanation: 'STAR: describe the Situation, Task, Action you took, and Result achieved' },
    { id: 'soft_010', question: 'What is the ideal body language during a job interview?', options: ['Arms crossed, leaning back', 'Looking at the floor when answering', 'Upright posture, natural eye contact, calm hand gestures', 'Constant nodding and agreeing'], correct: 2, explanation: 'Open, upright posture signals confidence and engagement' },
    { id: 'soft_011', question: 'When receiving critical feedback, the best response is:', options: ['Defend yourself immediately', 'Thank them, ask clarifying questions, and reflect', 'Stay silent and feel bad', 'Dismiss it if you disagree'], correct: 1, explanation: 'Receiving feedback well is a top professional skill employers look for' },
    { id: 'soft_012', question: 'Which skill is MOST important for remote work?', options: ['Speed typing', 'Written communication', 'Coding', 'Multitasking'], correct: 1, explanation: 'Remote work relies on clear async written communication across time zones' },
    { id: 'soft_013', question: 'What does "emotional intelligence" (EQ) primarily involve?', options: ['High IQ scores', 'Recognizing and managing your emotions and others', 'Being emotionally sensitive', 'Avoiding all conflicts'], correct: 1, explanation: 'EQ: self-awareness, self-regulation, empathy, social skills' },
    { id: 'soft_014', question: 'In a group discussion, speaking for too long without pausing:', options: ['Shows leadership', 'Demonstrates knowledge', 'Reduces participation and appears dominating', 'Normal and accepted'], correct: 2, explanation: 'Good GD participants make points concisely and invite others to respond' },
    { id: 'soft_015', question: 'If you do not know the answer to an interview question, you should:', options: ['Make up an answer confidently', "Say \"I don't know\" and go silent", "Honestly say you're unsure, then walk through your reasoning", 'Change the topic'], correct: 2, explanation: 'Honesty + reasoning shows intellectual humility — valued over bluffing' },
  ],
} as const;

export type QuestionCategory = keyof typeof QUESTION_BANK;
export type Question = typeof QUESTION_BANK[QuestionCategory][number];

export function getRandomQuestions(category: QuestionCategory, count = 10): Question[] {
  const pool = [...QUESTION_BANK[category]] as Question[];
  const shuffled = pool.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
