'use client';
import { useRef } from 'react';
import { PRSResult } from '@/types';

interface Props { name: string; prs: PRSResult; open: boolean; onClose: () => void; }

export default function ShareCardModal({ name, prs, open, onClose }: Props) {
  const cardRef = useRef<HTMLDivElement>(null);

  const download = async () => {
    if (!cardRef.current) return;
    try {
      const html2canvas = (await import('html2canvas')).default;
      const canvas = await html2canvas(cardRef.current, { backgroundColor: '#0A0A0F', scale: 2 });
      const link = document.createElement('a');
      link.download = `SmartPRS_${name.replace(/\s/g, '_')}.png`;
      link.href = canvas.toDataURL();
      link.click();
    } catch { alert('Download ready! Right-click the card to save.'); }
  };

  if (!open) return null;

  const color = prs.score >= 75 ? '#00C9A7' : prs.score >= 50 ? '#FFB347' : '#FF4D6D';
  const tier = prs.companyTiers[0] || '';

  return (
    <div className="modal-backdrop backdrop-blur-sm bg-[#1A1035]/60 flex items-center justify-center fixed inset-0 z-50 p-4" onClick={onClose}>
      <div className="flex flex-col items-center gap-6" onClick={e => e.stopPropagation()}>
        <div ref={cardRef} className="bg-white border-8 border-[#1A1035] p-8 rounded-3xl shadow-[12px_12px_0px_#1A1035] w-[340px] relative overflow-hidden">
          {/* Background pattern */}
          <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(#1A1035 2px, transparent 2px)', backgroundSize: '20px 20px' }}></div>
          
          <div className="relative z-10">
            <div className="flex items-center gap-3 mb-8 border-b-4 border-[#1A1035]/10 pb-4">
              <div className="w-10 h-10 rounded-xl bg-[#6C47FF] border-2 border-[#1A1035] shadow-[2px_2px_0px_#1A1035] flex items-center justify-center text-white font-black text-lg">S</div>
              <span className="text-xl font-black text-[#1A1035] uppercase tracking-tighter">Smart<span className="text-[#6C47FF]">PRS</span></span>
            </div>
            <p className="text-[10px] font-black text-[#1A1035]/50 mb-1 uppercase tracking-widest">Placement Readiness Score</p>
            <div className="flex items-end gap-2 mb-6">
              <span className="text-7xl font-black leading-none drop-shadow-[4px_4px_0px_#1A1035]" style={{ color }}>{Math.round(prs.score)}</span>
              <span className="text-[#1A1035] font-black text-2xl mb-2">/100</span>
            </div>
            <div className="bg-[#F8F7FF] border-4 border-[#1A1035] rounded-xl p-4 mb-6 shadow-[inset_0px_2px_4px_rgba(0,0,0,0.05)]">
              <p className="text-xl font-black text-[#1A1035] mb-1">{name}</p>
              <p className="text-sm font-bold" style={{ color }}>{prs.probability} Probability <span className="text-[#1A1035]/50">({prs.probabilityRange})</span></p>
            </div>
            <div className="grid grid-cols-5 gap-3 mb-6">
              {prs.weakAreas.map((a, i) => (
                <div key={i} className="text-center flex flex-col items-center">
                  <div className="text-[10px] font-black text-[#1A1035]/60 mb-2 uppercase tracking-widest">{a.skill.slice(0, 3)}</div>
                  <div className="h-16 w-8 bg-[#F8F7FF] border-2 border-[#1A1035] rounded-lg relative overflow-hidden shadow-[inset_0px_2px_4px_rgba(0,0,0,0.05)]">
                    <div className="absolute bottom-0 w-full transition-all border-t-2 border-[#1A1035]" style={{ height: `${a.score}%`, backgroundColor: a.severity === 'good' ? '#00C9A7' : a.severity === 'needs_improvement' ? '#FFB347' : '#FF4D6D' }} />
                  </div>
                  <div className="text-[10px] font-black text-[#1A1035] mt-2">{a.score}</div>
                </div>
              ))}
            </div>
            {tier && <div className="inline-block bg-[#6C47FF] text-white border-2 border-[#1A1035] px-3 py-1 rounded text-[10px] font-black uppercase tracking-widest shadow-[2px_2px_0px_#1A1035]">Ready for {tier}</div>}
            <p className="text-[10px] font-bold text-[#1A1035]/40 mt-6 text-center border-t-2 border-[#1A1035]/10 pt-4">Generated by SmartPRS — smartprs.vercel.app</p>
          </div>
        </div>
        <div className="flex gap-4">
          <button onClick={download} className="bg-[#00C9A7] text-[#1A1035] font-black uppercase tracking-wider py-3 px-6 rounded-xl border-4 border-[#1A1035] shadow-[4px_4px_0px_#1A1035] hover:shadow-[6px_6px_0px_#1A1035] hover:-translate-y-1 transition-all">📥 Download</button>
          <button onClick={onClose} className="bg-white text-[#1A1035] font-black uppercase tracking-wider py-3 px-6 rounded-xl border-4 border-[#1A1035] shadow-[4px_4px_0px_#1A1035] hover:shadow-[6px_6px_0px_#1A1035] hover:-translate-y-1 transition-all">Close</button>
        </div>
      </div>
    </div>
  );
}
