'use client';
import { useRef } from 'react';
import { PRSResult } from '@/types';

interface Props { name: string; prs: PRSResult; open: boolean; onClose: () => void; }

export default function ShareCardModal({ name, prs, open, onClose }: Props) {
  const cardRef = useRef<HTMLDivElement>(null);

  const download = async () => {
    if (!cardRef.current) return;
    try {
      const html2canvas = (await import('html2canvas')).default;
      const canvas = await html2canvas(cardRef.current, { backgroundColor: '#0A0A0F', scale: 2 });
      const link = document.createElement('a');
      link.download = `SmartPRS_${name.replace(/\s/g, '_')}.png`;
      link.href = canvas.toDataURL();
      link.click();
    } catch { alert('Download ready! Right-click the card to save.'); }
  };

  if (!open) return null;

  const color = prs.score >= 75 ? '#10B981' : prs.score >= 50 ? '#F59E0B' : '#EF4444';
  const tier = prs.companyTiers[0] || '';

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="flex flex-col items-center gap-6" onClick={e => e.stopPropagation()}>
        <div ref={cardRef} className="share-card">
          <div className="relative z-10">
            <div className="flex items-center gap-2 mb-6">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-brand-cyan to-brand-purple flex items-center justify-center text-white font-bold text-xs">S</div>
              <span className="text-sm font-bold text-white">SmartPRS</span>
            </div>
            <p className="text-xs text-gray-500 mb-1">PLACEMENT READINESS SCORE</p>
            <div className="flex items-end gap-3 mb-4">
              <span className="text-5xl font-extrabold" style={{ color }}>{Math.round(prs.score)}</span>
              <span className="text-gray-500 text-lg mb-1">/100</span>
            </div>
            <p className="text-lg font-bold text-white mb-1">{name}</p>
            <p className="text-sm mb-4" style={{ color }}>{prs.probability} Probability ({prs.probabilityRange})</p>
            <div className="grid grid-cols-5 gap-2 mb-4">
              {prs.weakAreas.map((a, i) => (
                <div key={i} className="text-center">
                  <div className="text-xs text-gray-500 mb-1">{a.skill.slice(0, 3)}</div>
                  <div className="h-12 bg-brand-border rounded-lg relative overflow-hidden">
                    <div className="absolute bottom-0 w-full rounded-lg transition-all" style={{ height: `${a.score}%`, backgroundColor: a.severity === 'good' ? '#10B981' : a.severity === 'needs_improvement' ? '#F59E0B' : '#EF4444' }} />
                  </div>
                  <div className="text-[10px] text-gray-400 mt-1">{a.score}</div>
                </div>
              ))}
            </div>
            {tier && <div className="badge badge-cyan text-xs">Ready for {tier}</div>}
            <p className="text-[10px] text-gray-600 mt-4">Generated by SmartPRS — smartprs.vercel.app</p>
          </div>
        </div>
        <div className="flex gap-3">
          <button onClick={download} className="btn-primary py-2 px-6">📥 Download Card</button>
          <button onClick={onClose} className="btn-secondary py-2 px-6">Close</button>
        </div>
      </div>
    </div>
  );
}
